// <auto-generated />
namespace PMSolution.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PatieBooIndicator : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PatieBooIndicator));
        
        string IMigrationMetadata.Id
        {
            get { return "202211062131290_PatieBooIndicator"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
